Sat, 30 Jul 2022 00:28:19-app-app.py-[line:1449]-ERROR-[日志信息]: Exception on /api/msg/find_chats [POST]
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\git-python\msg_servive\msgservice\views\message.py", line 252, in find_chats
    return jsonify(responseBuilder.build_response(ResCode.MESSAGE_FIND_SUCCESS.value,
  File "D:\Programs\Python\Python310\lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "D:\Programs\Python\Python310\lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "D:\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Programs\Python\Python310\lib\site-packages\flask_mongoengine\json.py", line 19, in default
    return superclass.default(self, obj)
  File "D:\Programs\Python\Python310\lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "D:\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CommandCursor is not JSON serializable
Sat, 30 Jul 2022 00:39:09-app-app.py-[line:1449]-ERROR-[日志信息]: Exception on /api/msg/find_chats [POST]
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\git-python\msg_servive\msgservice\views\message.py", line 249, in find_chats
    totalCount = chats.total
AttributeError: 'CommandCursor' object has no attribute 'total'
Sat, 30 Jul 2022 00:39:21-app-app.py-[line:1449]-ERROR-[日志信息]: Exception on /api/msg/find_chats [POST]
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\git-python\msg_servive\msgservice\views\message.py", line 249, in find_chats
    totalCount = chats.total
AttributeError: 'CommandCursor' object has no attribute 'total'
Sat, 30 Jul 2022 00:39:48-app-app.py-[line:1449]-ERROR-[日志信息]: Exception on /api/msg/find_chats [POST]
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\git-python\msg_servive\msgservice\views\message.py", line 252, in find_chats
    totalCount=totalCount, totalpage=totalpage,
NameError: name 'totalCount' is not defined
Sat, 30 Jul 2022 00:39:56-app-app.py-[line:1449]-ERROR-[日志信息]: Exception on /api/msg/find_chats [POST]
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\git-python\msg_servive\msgservice\views\message.py", line 252, in find_chats
    totalCount=totalCount, totalpage=totalpage,
NameError: name 'totalCount' is not defined
